[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-C",
    "link-arg=-Tsrc/linker.ld",
    "-C",
    "force-frame-pointers=yes",
    "-C",
    "link-arg=./target/riscv64gc-unknown-none-elf/release/trap/trap.o",          # 链接 trap.o
    "-C",
    "link-arg=./target/riscv64gc-unknown-none-elf/release/trap/kpthread_trap.o", # 链接 kpthread_trap.o
]
